# spin_version = "1"
# name = "tactics"
# description = "Prolog Home Page"
# trigger = { type = "http", base = "/" }
# version = "0.2.0"

# [[component]]
# id = "assets"
# description = "static files"
# files = [{ source = ".", destination = "/"}]
# [component.source]
# url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.2/spin_static_fs.wasm"
# digest = "sha256:65456bf4e84cf81b62075e761b2b0afaffaef2d0aeda521b245150f76b96421b"
# [component.trigger]
# route = "/..."


spin_manifest_version = 2

[application]
name = "tactics"
version = "0.2.0"
description = "Tactics!"

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-assets"
component = "assets"
route = "/..."

[component.assets]
description = "static files"
files = [{ source = ".", destination = "/" }]
[component.assets.source]
url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm"
digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148"
[component.assets.build]
command = "true"
watch = ["*.pl", "*.html", "*.css", "*.toml"]